bind-addr: 127.0.0.1:8080
auth: password
# code-server sets up self-signed certificate for you.
# See https://coder.com/docs/code-server/guide#using-a-self-signed-certificate
# While `setcap` command is used in the instruction, it is entirely optional and only necessary
# if you need the port to be 443 (or any number < 1024).
cert: false
# Separate directory for installing extensions so that volume mounting ~/.local/share/code-server
# does not result in old extensions overwriting newer ones installed during build.
# `~` will not be expanded to home directory, and since the home directory (user name) is variable,
# use /home/coder instead as it is a symlink to the user's actual home directory.
extensions-dir: /home/coder/.local/share/code-server-extensions
disable-workspace-trust: true
