bind-addr: 127.0.0.1:8080
auth: password
# code-server sets up self-signed certificate for you.
# See https://coder.com/docs/code-server/guide#using-a-self-signed-certificate
# While `setcap` command is used in the instruction, it is entirely optional and only necessary
# if you need the port to be 443 (or any number < 1024).
cert: false
disable-workspace-trust: true
