services:
  mise-test:
    image: jdxcode/mise:latest
    init: true
    depends_on:
      - mise-file-copy
    environment:
      - TZ
      - GITHUB_TOKEN
    entrypoint: bash
    volumes:
      - type: volume
        source: mise-test
        target: /mise
  mise-file-copy:
    image: alpine:latest
    volumes:
      - type: volume
        source: mise-test
        target: /mise/volume
      - type: bind
        source: ${PWD:?}/root/ctx/home/.config/mise
        target: /mise/bind
    entrypoint: sh -c "rm -rf /mise/volume/* && cp -rf /mise/bind/* /mise/volume/"
volumes:
  mise-test:
