#!/bin/bash

set -e

mkdir --parents ~/.local/{share,state}/nvim/ ~/.cde/mnt/single/.local/state/nvim/shada/
ln --symbolic --force ~/.cde/mnt/single/.local/state/nvim/{shada,trust} ~/.local/state/nvim/
ln --symbolic --force ~/.cde/mnt/hosthome/.local/share/nvim/lazy ~/.local/share/nvim/
ln --symbolic --force ~/.cde/mnt/hosthome/.local/state/nvim/lazy ~/.local/state/nvim/
