#!/bin/bash

set -e

mkdir --parents ~/.config/yazi/plugins
ln --symbolic --force ~/toybox/yazi/*.{lua,toml} ~/.config/yazi/
mise exec yazi --command 'ya pkg add yazi-rs/plugins:smart-enter && \
  ya pkg add yazi-rs/plugins:full-border && \
  ya pkg add yazi-rs/plugins:smart-filter && \
  ya pkg add yazi-rs/plugins:chmod && \
  ya pkg add yazi-rs/plugins:git && \
  ya pkg add yazi-rs/plugins:toggle-pane'
