export ANSIBLE_BECOME_PASSWORD_FILE := '.ansible_become_password'
export ANSIBLE_ROLES_PATH := source_directory() + "/.ansible/roles/"

playbook_check_flags := '--check --diff'
playbook := 'main.yml'

default:
        @just --list --unsorted

[private]
@echored +args:
	echo -e "\e[0;31m{{args}}\e[0;0m"

[private]
@echocyan +args:
	echo -e "\e[0;36m{{args}}\e[0;0m"

playbook tags *flags:
	ansible-playbook --tags={{tags}} {{flags}} {{playbook}}

playbook-check tags:
	just playbook {{tags}} {{playbook_check_flags}}

playbook-start-at-task task tags *flags:
	ansible-playbook --tags={{tags}} --start-at-task "{{task}}" --step {{flags}} {{playbook}}

lint:
	ansible-lint

galaxy-install:
	ansible-galaxy role install --role-file requirements.yml --roles-path .ansible/roles/

docker: galaxy-install
	just playbook docker

docker-check: galaxy-install
	just playbook-check docker

fish:
	just playbook fish

fish-check:
	just playbook-check fish

neovim:
	just playbook neovim

neovim-check:
	just playbook-check neovim

taskwarrior:
	just playbook taskwarrior

taskwarrior-check:
	just playbook-check taskwarrior

tmux:
	just playbook tmux

tmux-check:
	just playbook-check tmux

misc:
	just playbook misc

misc-check:
	just playbook-check misc

wsl:
	just --set playbook wsl.yml playbook wsl

wsl-check:
	just  --set playbook wsl.yml playbook-check wsl
