#!/bin/bash
set -e

script_dir=$(dirname "$0")

if [[ -r $script_dir/go-extra ]]; then
  # Use extra script to override versions and install additional go tools.
  # It is recommended to pin versions only when it is strictly necessary (e.g. for compatibility reason),
  # as the specified versions might get obsolete quickly.
  # GOLANGCI_LINT_VERSION=v1.59.0
  # MOCKGEN_VERSION=v0.4.0
  source ${script_dir}/go-extra
fi

# Installing golangci-lint via `go install` is not recommended
# ref: https://golangci-lint.run/welcome/install/#binaries
# The sample code installs golangci-lint to $(go env GOPATH)/bin but I changed to another location,
# because other tools installed via `go install` are placed under mise directory
# and $(go env GOPATH) is not in the PATH (just dont wanna be bothered).
mise exec go --command '\
  curl --location --silent --show-error --fail https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/.local/bin ${GOLANGCI_LINT_VERSION} && \
  go install -v golang.org/x/tools/cmd/goimports@latest && \
  go install -v golang.org/x/tools/cmd/gorename@latest && \
  go install -v golang.org/x/tools/gopls@latest && \
  go install -v golang.org/x/tools/cmd/callgraph@latest && \
  go install -v golang.org/x/tools/cmd/guru@latest && \
  go install -v github.com/segmentio/golines@latest && \
  go install -v github.com/fatih/gomodifytags@latest && \
  go install -v github.com/cweill/gotests/...@latest && \
  go install -v github.com/koron/iferr@latest && \
  go install -v github.com/josharian/impl@latest && \
  go install -v github.com/go-delve/delve/cmd/dlv@latest && \
  go install -v github.com/onsi/ginkgo/v2/ginkgo@latest && \
  go install -v github.com/tmc/json-to-struct@latest && \
  go install -v gotest.tools/gotestsum@latest && \
  go install -v go.uber.org/mock/mockgen@${MOCKGEN_VERSION:-latest} && \
  go install -v mvdan.cc/gofumpt@latest'
