#!/bin/bash
set -e

script_dir=$(dirname "$0")

if [[ -r $script_dir/go-extra ]]; then
  # Use extra script to override versions and install additional go tools.
  # It is recommended to pin versions only when it is strictly necessary (e.g. for compatibility reason),
  # as the specified versions might get obsolete quickly.
  # GOLANGCI_LINT_VERSION=v1.59.0
  # MOCKGEN_VERSION=v0.4.0
  source ${script_dir}/go-extra
fi

mise exec go --command '\
  go install -v golang.org/x/tools/cmd/goimports@latest && \
  go install -v golang.org/x/tools/gopls@latest && \
  go install -v golang.org/x/tools/cmd/callgraph@latest && \
  go install -v github.com/segmentio/golines@latest && \
  go install -v github.com/fatih/gomodifytags@latest && \
  go install -v github.com/cweill/gotests/...@latest && \
  go install -v github.com/koron/iferr@latest && \
  go install -v github.com/josharian/impl@latest && \
  go install -v github.com/go-delve/delve/cmd/dlv@latest && \
  go install -v github.com/onsi/ginkgo/v2/ginkgo@latest && \
  go install -v github.com/tmc/json-to-struct@latest && \
  go install -v gotest.tools/gotestsum@latest && \
  go install -v go.uber.org/mock/mockgen@${MOCKGEN_VERSION:-latest} && \
  go install -v mvdan.cc/gofumpt@latest'
