# With systemd enabled, dockerd automatically starts up when wsl launches
# source: https://dev.to/felipecrs/simply-run-docker-on-wsl2-3o8
- name: Enable systemd in WSL
  become: true
  tags:
    - wsl
  ansible.builtin.script:
    cmd: update_wsl_config.py
  args:
    executable: python3
  register: wsl_wsl_config_updated
  failed_when: wsl_wsl_config_updated.rc not in [0, 1]
  notify: Inform to restart WSL
