version: '3.9'
services:
  cde:
    environment:
      - RUST_VERSION=${VERSION}
    build:
      args:
        - RUSTUP_HOME=/home/${USER}/rust/rustup
        - CARGO_HOME=/home/${USER}/rust/cargo
    volumes:
      - type: volume
        source: rustpath
        target: /home/${USER}/rust
volumes:
  rustpath:
    name: rustpath_${VERSION}
    labels:
      prune: false
