version: '3.9'
services:
  cde:
    image: rust_cde:${RUST_VERSION}
    environment:
      - RUST_VERSION
    build:
      context: ./rust/ctx
      args:
        - RUST_VERSION
        - RUSTUP_HOME=/home/${USER}/rust/rustup
        - CARGO_HOME=/home/${USER}/rust/cargo
      labels:
        rust.version: ${RUST_VERSION:?}
    volumes:
      - type: volume
        source: rustpath
        target: /home/${USER}/rust
volumes:
  rustpath:
    name: rustpath_${RUST_VERSION}
    labels:
      prune: false
