- name: Check if latest taskwarrior is installed
  vars:
    binary_name: taskwarrior-tui
    binary_installed_version_cmd: taskwarrior-tui --version | awk '{print $2}'
    binary_latest_version_cmd: curl --location --silent --show-error --fail --retry 5 --retry-delay 3 https://api.github.com/repos/kdheepak/taskwarrior-tui/releases/latest | jq -r .tag_name | cut -c 2-
  ansible.builtin.include_role:
    name: binary
    tasks_from: latest_is_installed

- name: Install taskwarrior-tui
  when: not latest_binary_is_installed
  block:
    - name: Download taskwarrior-tui.deb
      ansible.builtin.command:
        cmd: ../github-latest-release-installer.sh kdheepak taskwarrior-tui taskwarrior-tui.deb /tmp/taskwarrior-tui.deb
        creates: /tmp/taskwarrior-tui.deb
    - name: Install taskwarrior-tui from deb file
      become: true
      ansible.builtin.apt:
        deb: /tmp/taskwarrior-tui.deb
        state: present
    - name: Remove taskwarrior-tui.deb
      ansible.builtin.file:
        path: /tmp/taskwarrior-tui.deb
        state: absent
