- name: Create docker config directory
  ansible.builtin.file:
    path: "{{ docker_config_dir }}"
    state: directory
    mode: "0755"

- name: Setup docker config
  ansible.builtin.script:
    cmd: setup_docker_config.py "{{ docker_config_dir }}/config.json" "{{ toybox_docker_dir }}/config.json"
  args:
    executable: python3
  register: docker_config_updated
  changed_when: docker_config_updated.rc == 0
  failed_when: docker_config_updated.rc not in [0, 1]

- name: Check if cde_shared docker volume exists
  ansible.builtin.command:
    cmd: docker volume inspect cde_shared
  register: cde_shared_volume_info
  failed_when: false
  changed_when: false

- name: Create cde_shared docker volume
  become: true
  ansible.builtin.command:
    # White `docker volume create` itself is already idempotent (no error even if the volume exists),
    # the existence of volume is checked in advance so that `changed_when` can be added.
    cmd: docker volume create --label prune=false cde_shared
  when: cde_shared_volume_info.rc != 0
  changed_when: cde_shared_volume_info.rc != 0
