version: '3.9'
services:
  cde:
    environment:
      - CGO_ENABLED=${CGO_ENABLED:-0}
    build:
      labels:
        go.version: ${VERSION:?}
    volumes:
      - type: volume
        source: gopath
        target: /home/${USER}/go
volumes:
  gopath:
    name: gopath_${VERSION}
    labels:
      prune: false
