version: '3.9'
services:
  cde:
    image: go_cde:${GO_VERSION:?}
    environment:
      - CGO_ENABLED=${CGO_ENABLED:-0}
    build:
      context: ./go/ctx
      args:
        - GO_VERSION=${GO_VERSION:?}
      labels:
        go.version: ${GO_VERSION:?}
    volumes:
      - type: volume
        source: gopath
        target: /home/${USER}/go
volumes:
  gopath:
    name: gopath_${GO_VERSION}
    labels:
      prune: false
