version: '3.9'
services:
  cde:
    image: ${COMPOSE_PROJECT_NAME}_cde:${GO_VERSION}
    environment:
      - CGO_ENABLED=${CGO_ENABLED:-0}
    build:
      args:
        - GO_VERSION
    volumes:
      - type: volume
        source: gopath
        target: /home/${USER:-mojito}/go
volumes:
  gopath:
    name: gopath_${GO_VERSION}
