version: '3.9'
services:
  cde:
    environment:
      - CGO_ENABLED=${CGO_ENABLED:-0}
    build:
      args:
        - GO_VERSION
    volumes:
      - type: volume
        source: gopath
        target: /home/${USER:-mojito}/go
volumes:
  gopath:
    external: true
