set shell := ['/usr/bin/bash', '-c']

export USER_ID := `id -u`
export USER_NAME := `whoami`
export GROUP_ID := `id -g`
export GROUP_NAME := `groups | cut -d ' ' -f1`

mod playbooks

export PATH := env_var('HOME') / '.local/bin:' + env_var('PATH')

default:
	@just --list --unsorted

github_repo_subpath := 'personal.github.com/Toraja'
github_host_user := 'personal.github.com:Toraja'
toybox_repo_url := 'git@' + github_host_user / 'toybox.git'
cde_repo_url := 'git@' + github_host_user / 'cde.git'

# Clone necessary repositories, setup gitconfig and create symlinks to the repositories
repositories:
	#!/usr/bin/env bash
	if [[ ! -d ~/toybox ]]; then
		git clone {{toybox_repo_url}} ~/toybox
	fi
	if [[ ! -e ~/.gitconfig ]]; then
		cat ./fixtures/gitconfig > ~/.gitconfig
	elif ! diff --brief ./fixtures/gitconfig ~/.gitconfig; then
		echo "gitconfig is in an unexpected state. You might wanna check that the change is valid."
	fi
	ghq_root=$(ghq root)
	if [[ -d ~/toybox && ! -L ~/toybox ]]; then
		mkdir --parents ${ghq_root}/{{github_repo_subpath}} && \
			mv ~/toybox ${ghq_root}/{{github_repo_subpath}} && \
			ln --symbolic ${ghq_root}/{{github_repo_subpath}}/toybox ~/toybox
	fi
	if [[ -d ~/cde && ! -L ~/cde ]]; then
		mv ~/cde ${ghq_root}/{{github_repo_subpath}} && \
			ln --symbolic ${ghq_root}/{{github_repo_subpath}}/cde ~/cde
	fi

ansible:
	sudo apt-get update
	sudo apt-get install --no-install-recommends --yes pipx
	# Install ansible directly with pipx rather than with mise as I don't need to switch versions
	# and want to minimise disk usage
	pipx install --include-deps ansible

[group('Test')]
test:
	docker compose run --rm test

[group('Test')]
build-testenv *bakeflag:
	docker buildx bake {{bakeflag}} test

[group('Test')]
renew-test-base:
	docker pull ubuntu:latest
