[tools]
bat = { version = 'latest' }
bottom = { version = 'latest' }
cheat = { version = 'latest', postinstall = 'mise run postinstall:cheat' }
direnv = { version = 'latest', postinstall = 'mise run postinstall:direnv' }
fd = { version = 'latest' }
fx = { version = 'latest' }
fzf = { version = 'latest', postinstall = 'mise run postinstall:fzf' }
ghq = { version = 'latest' }
github-cli = { version = 'latest', postinstall = 'mise run postinstall:github-cli' }
glow = { version = 'latest', postinstall = 'mise run postinstall:glow' }
jq = { version = 'latest' }
just = { version = 'latest', postinstall = 'mise run postinstall:just' }
lazydocker = { version = 'latest' }
lazygit = { version = 'latest', postinstall = 'mise run postinstall:lazygit' }
node = { version = 'latest', postinstall = 'mise run postinstall:node' }
regctl = { version = 'latest', postinstall = 'mise run postinstall:regctl' }
ripgrep = { version = 'latest', postinstall = 'mise run postinstall:ripgrep' }
shfmt = { version = 'latest' }
usage = { version = 'latest' }
uv = { version = 'latest' }
xh = { version = 'latest', postinstall = 'mise run postinstall:xh' }
yazi = { version = 'latest', postinstall = 'mise run postinstall:yazi' }
