# ----------------------------
# Added by host setup makefile
# ----------------------------
if [[ ! ${PATH} =~ "${HOME}/.local/bin" ]]; then
  export PATH=${PATH}:${HOME}/.local/bin
fi

# disable Ctrl-s and Ctrl-q keybind
stty -ixon

# Required to use wgl (WSL GUI component)
export LIBGL_ALWAYS_INDIRECT=1

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
  for rc in ~/.bashrc.d/*; do
    if [ -f "$rc" ]; then
      . "$rc"
    fi
  done
fi
unset rc
